var tasks = [
    "Sprinting Through the Storm",
    "If You Can't Take the Heat",
    "Rave Time",
    "Where We Droppin'?",
    "Shh, This is a Library!",
    "Sprinting Through Utah",
    "Down, Boy",
    "Payday!",
    "POGDOGTRACK",
    "Hot Date",
    "Sprinting Through the Bayou",
    "Pest Control",
    "Indiana Cooper",
    "Raccoon Gumbo",
    "Fish Fry",
    "Sprinting Through the Mountains",
    "You Monster",
    "No More Kung-Fu!",
    "Like a Dragon",
    "I Got You Covered",
    "Cloudy with a Chance of Meatballs",
    "Blue Screen of Death",
    "The Ultimate Disguise",
    "Haven't Had to Do This in a While",
    "Owl Historian",
    "Foxy Lady",
    "The Water's Fine",
    "Rock N' Roll",
    "Bottle Hoarder",
    "All Part of the Plan",
    "1-UP!",
    "The Luck of the Irish",
    "Shortcut!",
    "Going UP",
    "Navigate Like Drake"
];

var bosses  =  [
    "Frog Legs",
    "Giving the Dog a Bone",
    "Dance, Dance, Ruby",
    "Pandas Aren't Always Cute",
    "Oh No He Didn't"
]