var tasks = [
    ["Sprinting Through the Storm", "Complete any World 1 MTS (Master Thief Sprint)."],
    ["If You Can't Take the Heat","Slam shut all the furnaces in Into the Machine or Fire Down Below at least once each. There are x in ITM and 5 in FDB."],
    ["Rave Time","Collect the key in the crabs minigame, Treasure in the Depths, in World 1."],
    ["Where We Droppin'?","Hear Raleigh say “fortnite” (or other language equivalent) in The Gunboat Graveyard in World 1. Listen to the full dialogue from start to finish."],
    ["Shh, This is a Library!","Take the barrel disguise all the way to the key in A Cunning Disguise in World 1."],
    ["Sprinting Through Utah","Complete any World 2 MTS (Master Thief Sprint)."],
    ["Down, Boy","Defeat all dog enemies in any level in World 2."],
    ["Payday!","Collect the coins from the rotating doghouse in the Boneyard Casino in World 2."],
    ["POGDOGTRACK","Collect the key in At the Dog Track in World 2."],
    ["Hot Date","Watch the “date” cutscene with Carmelita before the chase sequence begins in Two to Tango in World 2."],
    ["Sprinting Through the Bayou","Complete any World 3 MTS (Master Thief Sprint)."],
    ["Pest Control","Defeat all mosquito enemies and/or spider enemies in any level in World 3. (Viable levels: The Dread Swamp Path, Lair of the Beast, A Grave Undertaking, Descent Into Danger)."],
    ["Indiana Cooper","Escape the giant snake in Lair of the Beast in World 3 by following the casual route. This is considered complete at the end of the chase sequence once the cutscene for the snake leaving has finished."],
    ["Raccoon Gumbo","Allow the bomb-toting roosters to defeat you after collecting 20 or more chickens in Down Home Cooking in World 3, then collect the key. You must take a full death to the roosters, exhausting all charms and then dying properly."],
    ["Fish Fry","Restart the fish minigame, Piranha Lake in World 3, after lighting 15 or more torches, then collect the key."],
    ["Sprinting Through the Mountains","Complete any World 5 MTS (Master Thief Sprint)."],
    ["You Monster","Witness the Panda King bury an entire village in snow in A Perilous Ascent in World 4. This is considered completed by watching the entire cutscene."],
    ["No More Kung-Fu!","Defeat all the monkey enemies training on balance poles in Flaming Temple of Flame in World 4."],
    ["Like a Dragon","Collect the key in Duel by the Dragon in World 4."],
    ["I Got You Covered","Protect Murray and collect the key in The King of the Hill in World 4."],
    ["Cloudy with a Chance of Meatballs","Let the falling rocks kill you in A Hazardous Path in World 5."],
    ["Blue Screen of Death","Restart the slugs minigame, Burning Rubber in World 5, after collecting 25 or more computers, then complete the minigame."],
    ["The Ultimate Disguise","Reach Carmelita\’s prison chamber with the protection of a barrel in A Daring Rescue in World 5."],
    ["Haven't Had to Do This in a While","Complete the hacking minigame in Bentley Comes Through in World 5. This requires fully completing the level all the way through to the end, including the final monologue cutscene."],
    ["Owl Historian","Watch the opening cutscene with Bentley\’s jetpack training and Clockwerk\’s dialogue at the beginning of A Strange Reunion."],
    ["Foxy Lady","Open the vault in Paris to collect Sly\’s criminal record file from Inspector Carmelita Fox. This is considered completed upon opening the vault under the same rules as in the All Vaults category."],
    ["The Water's Fine","Collect the Dive ability from a vault. The run must also end with Dive being available to the runner (no save/load-duping it away)."],
    ["Rock N' Roll","Collect the Roll ability from a vault. The run must also end with Roll being available to the runner (no save/load-duping it away)."],
    ["Bottle Hoarder","Collect all bottles in any level."],
    ["All Part of the Plan","Collect the Blueprints in any World. This requires opening 3 vaults within the same world."],
    ["1-UP!","Gain an extra life by exceeding the 99-coin maximum while holding a golden lucky charm."],
    ["The Luck of the Irish","Collect all free-standing lucky charms in any level that contains at least two, then use them all before collecting the key at the end of the level. (Viable levels: Two to Tango, Grave Undertaking)."],
    ["Shortcut!","Unlock the gate blocking the second half of any world by collecting three keys and opening the gate. (World 1: Unlock and destroy the generator. World 2: Unlock the car and destroy the boards blocking access to the casino. World 3: Unlock the bone gate with the help of a giant snake. World 4: Unlock the roof hatch with fireworks.)"],
    ["Going UP","Access the boss level of any world using the intended method. This requires collecting all 7 keys in any world then using the intended method to access the final boss fight. (World 1: Use the cannon to go to The Eye of the Storm. World 2: Use the Muggshot elevator to go to Last Call. World 3: Use the high-pressure soup lid to go to A Deadly Dance. World 4: Use the fireworks to go to Flame-Fu!)."],
    ["Navigate Like Drake","Enter all levels in any two Worlds (minimum) and show off the fully revealed World maps."]
];

var bosses  =  [
    ["Frog Legs", "Defeat Raleigh the Frog in World 1 and unlock the next world."],
    ["Giving the Dog a Bone","Defeat Muggshot in World 2 and unlock the next world."],
    ["Dance, Dance, Ruby","Defeat Mz. Ruby in World 3 and unlock the next world."],
    ["Pandas Aren't Always Cute","Defeat Panda King in World 4 and unlock the next world."],
    ["Oh No He Didn't","Defeat Clockwerk in World 5 and take back the Thievius Raccoonus!"]
]